### ISSUE TITLE
咋写插件啊?可以回复的那种

### ISSUE THREAD

**Issue by 2970884077** [uebian/QQRobot#4]

**Comment by uebian** [comment]
您可以参见插件的开发文档:https://github.com/uebian/QQRobot/blob/master/Plugin.md
如果仍有问题可以提出issue

**Comment by 2970884077** [comment]
并实现几个回调方法（不解释，基本上看方法名就知道是啥方法）



这里不会弄

**Comment by 2970884077** [comment]
能不能写个插件demo啊?

**Comment by uebian** [comment]
我们会考虑近期发布一个demo

**Comment by 2970884077** [comment]
谢谢

**Comment by 2970884077** [comment]
请问demo写好了么?

**Comment by uebian** [comment]
> 请问demo写好了么?

最近事情比较多，可能需要等一段时间

**Comment by uebian** [comment]
您好，插件demo已经发布

**Comment by 2970884077** [comment]
链接呢

**Comment by uebian** [comment]
> 链接呢

https://github.com/uebian/QQRobot/tree/master/demo
