### ISSUE TITLE
如何写插件

### ISSUE THREAD

**Issue by 2970884077** [uebian/QQRobot#5]
> 这里面咋写
@Override

		public void onMessageHandler(QQMessage message)
		
		{
}求

**Comment by uebian** [comment]
您好，你可以在此对消息进行相应，参见插件demo

**Comment by 2970884077** [comment]
谢谢，我弄到了

**Comment by 2970884077** [comment]
我想问一下，为什么抓包软件抓不到机器人发消息

**Comment by uebian** [comment]
> 我想问一下，为什么抓包软件抓不到机器人发消息

请新开issue讨论，谢谢
