### ISSUE TITLE
什么时候更新啊?

### ISSUE THREAD

**Issue by 2970884077** [uebian/QQRobot#7]
……

**Comment by uebian** [comment]
您好，本项目基本处于被放弃状态，您可以参见另外一个项目：https://github.com/mamoe/mirai

**Comment by 2970884077** [comment]
这个是kotlin写的，不是java的

**Comment by 2970884077** [comment]
可以更新几个接口吗

**Comment by uebian** [comment]
您可以在新的issue中提出feature request，但不能保证能在短时间内实现

**Comment by 2970884077** [comment]
为什么

**Comment by uebian** [comment]
因为PCTIM协议分析起来难度比较大，相比而言AndroidQQ协议分析起来难度小很多。

**Comment by 2970884077** [comment]
那你不弄个安卓机器人

**Comment by uebian** [comment]
mirai将来会有android-console版本，并很大可能由我维护

**Comment by 2970884077** [comment]
将来，多久

**Comment by 2970884077** [comment]
SendPackageFactory.java是接口用的吗

**Comment by uebian** [comment]
> 将来，多久

目前已经在开发阶段了，时间未知

**Comment by uebian** [comment]
> SendPackageFactory.java是接口用的吗

针对性的问题请在新的issue中讨论，谢谢
